version: "2.1"
services:
  nginx:
    image: dptablo/react-nextjs-template-nginx:1.1.0
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: react-nextjs-template-nginx
    ports:
      - "8888:80"
    depends_on:
      - web
  web:
    image: dptablo/react-nextjs-template:1.1.0
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-production
    container_name: react-nextjs-template
    expose:
      - "3333"